# Site settings
title: Peter van Onselen
description: > # this means to ignore newlines until "baseurl:"
  Personal website and portfolio of Peter van Onselen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.petervanonselen.com" # the base hostname & protocol for your site
google_analytics: G-WVL7NL8PB9

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Feed settings
feed:
  posts_limit: 20

# Exclude from processing
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Author information (for structured data and SEO)
author:
  name: Peter van Onselen
  email: augury_upsurge.17@icloud.com
  uri: "https://www.petervanonselen.com"

# Social links
social:
  name: Peter van Onselen
  links:
    - https://github.com/vanonselenp
    - https://www.linkedin.com/in/peter-van-onselen-a46b1b2b
  github: vanonselenp
  linkedin: peter-van-onselen-a46b1b2b
  email: augury_upsurge.17@icloud.com

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
